on:
    - push
    - pull_request

jobs:
    install-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
                  node-version-file: ".node-version"

            - name: Install dependencies
              run: pnpm install

            - name: Build .env
              env:
                  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
                  AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
                  AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
                  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
              run: |
                  echo "AUTH_SECRET=$AUTH_SECRET" >> .env
                  echo "AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID" >> .env
                  echo "AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET" >> .env
                  echo "DATABASE_URL=$DATABASE_URL" >> .env
                  echo "GROQ_API_KEY=$GROQ_API_KEY" >> .env
                  echo "BLOB_READ_WRITE_TOKEN=$BLOB_READ_WRITE_TOKEN" >> .env

            - name: Lint
              run: pnpm check

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm build --no-lint
